### ISSUE TITLE
Config to limit which errors can be used with baseline

### ISSUE THREAD

**Issue by Zeckie** [KotlinIsland/basedmypy#195] opened 2022-02-17 06:20 UTC
My baseline contained one error:
```
{
"line": 256,
"code": "misc",
"message": "Expression type contains \"Any\" (has type \"List[Dict[str, Any]]\")"
}
```
but that hid another error that geniune mypy picked up:
```redacted.py:256: error: TypedDict key must be a string literal; expected one of ("redacted", "redacted") [misc]```

Would be useful to be able to configure it so when the baseline is being used to supress existing errors only, there is some option to specify which mypy options are new (eg. `disallow_any_explicit = true`). With that option, only those errors would be used for baselining (i.e. any errors that would be raised without that option would not be able to be added to the baseline, and would not be suppressed by anything already in the baseline).

**Comment by KotlinIsland** [comment] 2022-02-17 06:38
Duplicate of  #114

**Closed** 2022-02-17 06:39 UTC
Labels: duplicate, feature
