### ISSUE TITLE
Detailed documentation on baseline features

### ISSUE THREAD

**Issue by Zeckie** [KotlinIsland/basedmypy#201] opened 2022-02-20 03:02 UTC
Detailed documentation (at a level similar to https://mypy.readthedocs.io/en/stable/running_mypy.html) for the baseline features such as `--write-baseline`

**Comment by KotlinIsland** [comment] 2022-02-20 07:22
This looks like a duplicate of #144

**Closed** 2022-03-03 06:31 UTC
Labels: documentation, duplicate
