### ISSUE TITLE
option to prevent certain error codes from being baselined

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#150] opened 2022-01-12 06:29 UTC
certain error codes are dangerous to baseline because they can cause other errors to go undetected:
```py
def foo(value: str = None) -> None: #baselined "no implicit optional" error
  bar: str = value # new code, no error because it's treated as `str` even tho it's actually `str | None`
```

**Comment by KotlinIsland** [comment] 2022-01-12 06:36
dupe of #114

**Closed** 2022-01-12 06:42 UTC
Labels: feature, basedline, error codes
