### ISSUE TITLE
inferred overload return types don't work with generics in some cases

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#741] opened 2024-08-19 05:15 UTC
```py
@overload
def foo(value: str) -> int: ...


@overload
def foo[T](value: T) -> T: ...


def foo[T](value: T | str):
    if isinstance(value, str):
        return 1
    return value  # Incompatible return value type (got "T@foo", expected "int | T@foo")
```

**Comment by KotlinIsland** [comment] 2024-08-19 05:20
duplicate of #385?

**Comment by DetachHead** [comment] 2024-08-19 05:30
dont think so, this issue seems to have been introduced in the latest release

**Comment by KotlinIsland** [comment] 2024-08-28 12:15
i think it is the same underlying issue, i'm going to merge it

**Closed by KotlinIsland** 2024-08-28 12:15 UTC
