### ISSUE TITLE
Store offset within class / function in the baseline

### ISSUE THREAD

**Issue by Zeckie** [KotlinIsland/basedmypy#183] opened 2022-02-08 03:25 UTC
Locations of errors stored in baseline file are currently using filename and line number within that file.

Sometimes, making a change such as adding a new function to a file moves the other lines within the file far enough that they are not recognised (If I remember correctly, they can move up to 50 lines and still be recognised). 

Would it be possible to also record the class / function(s), and an offset relative to the function `def`? That way, if a one function is added / modified, the baselined errors in a different function will still reliably be recognised.

**Comment by KotlinIsland** [comment] 2022-02-08 03:26
Related #134

**Comment by KotlinIsland** [comment] 2022-03-04 07:56
Groundwork for this this is implemented in #212

**Comment by KotlinIsland** [comment] 2022-08-13 08:17
Merged this with #134

Duplicate of #134

**Closed by KotlinIsland** 2022-08-13 08:17 UTC
Labels: feature, basedline, p-2
