### ISSUE TITLE
flag to rewrite baseline if pass

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#106] opened 2021-12-17 00:24 UTC
otherwise it's possible to fix errors, forget to rewrite the baseline, then those same errors could potentially get re-introduced later.

in fact maybe this flag should be enabled by default?

**Comment by KotlinIsland** [comment] 2021-12-21 05:08
This looks like a dupe of #84, can you close one of them please.

**Closed** 2021-12-21 05:09 UTC
Labels: duplicate, feature, basedline
